#!/usr/bin/env python3
"""Write gems_all.h: every fn/*.h and sharc/*.h, and the tables gems.h wants.
Only functions that are defined go in the tables, so a half-converted tree
builds. Usage: gen_all.py [out_path]  (default: gems_all.h beside this file)."""
import os, re, sys, glob
D = os.path.dirname(os.path.abspath(__file__))
out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(D, 'gems_all.h')
fn_files = sorted(glob.glob(os.path.join(D, 'fn', '*.h')))
sh_first = [os.path.join(D, 'sharc', f) for f in ('state.h', 'helpers.h')]
sh_first = [f for f in sh_first if os.path.exists(f)]
sh_files = sorted(f for f in glob.glob(os.path.join(D, 'sharc', '*.h')) if f not in sh_first)
defined = set()
for f in fn_files + sh_first + sh_files:
    for m in re.finditer(r'^static\s+[\w\s\*]+?\b(g(?:fn|cop)_\w+)\s*\([^;{]*\)\s*\{', open(f).read(), re.M):
        defined.add(m.group(1))
# A Gems handler with an empty body: Gems drops the command, the firmware
# answers it. The board keeps ours for those, so the i960's replies arrive.
empty = set()
for f in sh_files:
    for m in re.finditer(r'^static\s+void\s+(gcop_[0-9a-f]{2})\s*\(void\)\s*\{\s*(?:/\*.*?\*/\s*)*\}', open(f).read(), re.M | re.S):
        empty.add(m.group(1))
# The profile hooks inside trapped functions that the C runs itself
# (gems_inner(0x...) in fn/*.h): m2-hle2 then lets that profile use the trap.
inner = sorted({int(m.group(1), 16) for f in fn_files
                for m in re.finditer(r'\bgems_inner\(\s*(0x[0-9A-Fa-f]+)\s*\)', open(f).read())})
traps = []
for l in open(os.path.join(D, 'traps.txt')):
    t, a, rest = l.split(' ', 2)
    m = re.match(r"\('(\w+)'", rest.strip())
    if m and 'gfn_' + m.group(1) in defined:
        traps.append((int(a, 16), m.group(1)))
ops = {}
# The argument counts come from gems-decomp's SHARC/INDEX.md (the decomp/ submodule).
INDEX = os.path.join(D, 'decomp', 'SHARC', 'INDEX.md')
if not os.path.exists(INDEX):
    sys.exit('gen_all.py: no %s; run: git submodule update --init decomp' % INDEX)
for l in open(INDEX):
    m = re.match(r'\| ([0-9a-f]{2}) \| (\d+) \| (\d+) \| [0-9a-f]+ \| (\S+) \|', l)
    if m: ops[int(m.group(1), 16)] = (int(m.group(2)), m.group(4))
L = ['/* Generated by gen_all.py. */', '#pragma once']
L += ['#include "%s"' % os.path.relpath(f, D) for f in sh_first + sh_files + fn_files]
if inner:
    L.append('#define GEMS_INNER_SITES %s' % ', '.join('0x%08Xu' % a for a in inner))
L.append('static const gems_trap_t gems_traps[] = {')
L += ['    { 0x%05X, gfn_%s, "%s" },' % (a, n, n) for a, n in traps] or ['    { 0, 0, 0 },']
L.append('};')
L.append('static const size_t gems_trap_count = %d;' % len(traps))
L.append('static const gems_cop_op_t gems_cop_ops[GEMS_COP_OPS] = {')
for op in sorted(ops):
    if 'gcop_%02x' % op in defined and 'gcop_%02x' % op not in empty:
        args, name = ops[op]
        a = 'COP_ARGS_STREAM' if op == 0x80 else str(args)
        L.append('    [0x%02X] = { gcop_%02x, %s, "%s" },' % (op, op, a, name if name != '-' else 'op_%02x' % op))
L.append('};')
have = lambda n: n in defined
L.append('static void gems_cop_impl_reset(void) { %s }' % ('gcop_reset();' if have('gcop_reset') else ''))
L.append('static void gems_zanzou_begin(void) { %s }' % ('gcop_zanzou_begin();' if have('gcop_zanzou_begin') else ''))
L.append('static bool gems_zanzou_feed(uint32_t w) { %s }' % ('return gcop_zanzou_feed(w);' if have('gcop_zanzou_feed') else '(void)w; return true;'))
text = '\n'.join(L) + '\n'
# Left alone when nothing changed, so a build that runs this every time stays incremental.
if not os.path.exists(out) or open(out).read() != text:
    open(out, 'w').write(text)
print('%s: %d traps, %d COP ops' % (out, len(traps), sum(1 for l in L if l.startswith('    [0x'))))
